version: '3.2'

services:
  ghost:
    image: ghost:latest
    restart: always
    environment:
      url: http://sawied.top
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password-secret
      database__connection__database: ghost
  db:
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: password-secret
   volumes:
     - type: bind
       source: /var/data/mysql
       target: /var/lib/mysql
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - type: bind
        source: /var/data/letsencrypt
        target: /var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9080:8080"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password-secret
      
       
     
     
     
