apiVersion: v1
kind: Pod
metadata:
  name: microservice-social-cloud
  namespace: sawied
spec:
  containers:
    - image: microservice/microservice-oauth2-social:0.0.1-SNAPSHOT
      name: microservice-social-cloud
      imagePullPolicy: ifNotPresent
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
           name: git-secret
