apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-social-cloud
  labels:
    app: microservice-social-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-social-cloud
  template:
    metadata:
      labels:
        app: microservice-social-cloud
    spec:
      containers:
        - name: microservice-social-cloud
          image: microservice-social-cloud:0.0.1-SNAPSHOT
          ports:
            - containerPort: 80