apiVersion: v1
kind: Pod
metadata:
  name: microservice-social-cloud
  labels:
    env: dev
    app: microservice-social-cloud
  namespace: sawied
spec:
  containers:
    - image: microservice/microservice-oauth2-social:0.0.1-SNAPSHOT
      name: microservice-social-cloud
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
           name: git-secret

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-social-cloud-service
  namespace: sawied
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
  selector:
    app: microservice-social-cloud
