apiVersion: v1
kind: Pod
metadata:
  name: microservice-social-cloud
  namespace: sawied
  annotations: github_login
spec:
  containers:
    - image: microservice-social-cloud:0.0.1-SNAPSHOT
      name: microservice-social-cloud
      ports:
        - containerPort: 80
      envFrom:
        secretRef:
          name: git-secret