spring:
  security:
    user:
      name: danan
      password: password
  data:
    datasource:
      driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true

