------=_001_NextPart873717258062_=----
Content-Type: multipart/alternative;
	boundary="----=_002_NextPart168841144224_=----"

------=_002_NextPart168841144224_=----
Content-Type: text/plain; charset="GB2312"
Content-Transfer-Encoding: base64

VGVzdCAxMTIwMA0KDQoNCg0KQXJjaGl0ZWN0dXJlciwgUHJvZHVjdCBJbnRlZ3JhdGlvbiBTZXJ2
aWNlIERlcGFydG1lbnQsIEphbWVzIFggVyBaaGFuZw0KVEVMKzg2IDE4NjAyOTU3NzQ1DQpBRERS
IDNGLCBGMSBDIEJ1aWxkaW5nLCBDaGluYXNvZnQgSW50ZXJuYXRpb25hbCwgMzYzOSBZdW5zaHVp
IDFzdCBSb2FkLCBIaWdoLXRlY2ggWm9uZSwgWGknYW4NCnpoYW5neGlhb3dlaUBjaGluYXNvZnRp
LmNvbSB8IHd3dy5jaGluYXNvZnRpLmNvbQ0KIA0KVGhpcyBtZXNzYWdlIChpbmNsdWRpbmcgYW55
IGF0dGFjaG1lbnRzKSBjb250YWlucyBjb25maWRlbnRpYWwgaW5mb3JtYXRpb24gaW50ZW5kZWQg
Zm9yIGEgc3BlY2lmaWMgaW5kaXZpZHVhbCBhbmQgcHVycG9zZSwgYW5kIGlzIHByb3RlY3RlZCBi
eSBsYXcuIElmIHlvdSBhcmUgbm90IHRoZSBpbnRlbmRlZCByZWNpcGllbnQsIHlvdSBzaG91bGQg
ZGVsZXRlIHRoaXMgbWVzc2FnZSAtIGFueSBkaXNjbG9zdXJlLCBjb3B5aW5nLCBvciBkaXN0cmli
dXRpb24gb2YgdGhpcyBtZXNzYWdlLCBvciB0aGUgdGFraW5nIG9mIGFueSBhY3Rpb24gYmFzZWQg
b24gaXQsIGlzIHN0cmljdGx5IHByb2hpYml0ZWQuDQoNCg==

------=_002_NextPart168841144224_=----
Content-Type: text/html; charset="GB2312"
Content-Transfer-Encoding: quoted-printable

<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charse=
t=3DGB2312"><style>body { line-height: 1.5; }p { margin-top: 0px; margin-b=
ottom: 0px; }body { font-size: 10.5pt; font-family: Tahoma; color: rgb(0, =
0, 0); line-height: 1.5; }body { font-size: 10.5pt; font-family: Tahoma; c=
olor: rgb(0, 0, 0); line-height: 1.5; }</style></head><body>=0A<div><span>=
</span>Test 11200</div>=0A<div><br></div><hr style=3D"width: 210px; height=
: 1px;" color=3D"#b5c4df" size=3D"1" align=3D"left">=0A<div><span><p class=
=3D"MsoNormal" style=3D"margin: 0px 0cm; text-align: justify; font-family:=
 Calibri, sans-serif; line-height: normal;"><span lang=3D"EN-US"><img bord=
er=3D"0" width=3D"303" height=3D"16" id=3D"_x0000_i1033" src=3D"cid:_Foxma=
il.1@809225ca-f74d-7c0a-5f4c-37dea29b83a5" alt=3D"cid:image001.png@01D3F44=
2.49D7BA90" style=3D"max-width: 100%; height: auto !important;"><o:p></o:p=
></span></p><p class=3D"MsoNormal" style=3D"margin: 0px 0cm; text-align: j=
ustify; font-family: Calibri, sans-serif; line-height: 10pt;"><span lang=
=3D"EN-US" style=3D"font-size: 9pt; color: rgb(127, 127, 127);"><span styl=
e=3D"background-color: rgba(0, 0, 0, 0); font-family: 'Calibri, sans-serif=
'; line-height: 1.5;">Architecturer</span>, Product Integration Service De=
partment, James X W Zhang<o:p></o:p></span></p><p class=3D"MsoNormal" alig=
n=3D"left" style=3D"margin: 0px 0cm; font-family: Calibri, sans-serif; lin=
e-height: 9pt;"><span lang=3D"EN-US" style=3D"font-size: 9pt; font-family:=
 =CB=CE=CC=E5; color: rgb(127, 127, 127);"><img border=3D"0" width=3D"416"=
 height=3D"5" id=3D"_x0000_i1032" src=3D"cid:_Foxmail.1@0816baed-6ddc-3b9a=
-67e6-7a59d4354048" alt=3D"cid:image004.png@01CE733F.7F61E8E0" style=3D"ma=
x-width: 100%; height: auto !important;"><o:p></o:p></span></p><p class=3D=
"MsoNormal" style=3D"margin: 0px 0cm; text-align: justify; font-family: Ca=
libri, sans-serif; line-height: 21pt;"><b><span lang=3D"EN-US" style=3D"co=
lor: rgb(127, 127, 127);"><img border=3D"0" width=3D"170" height=3D"17" id=
=3D"=CD=BC=C6=AC_x0020_1" src=3D"cid:_Foxmail.1@915630e2-8567-ac54-e109-1d=
fca433392b" alt=3D"logo_email" style=3D"max-width: 100%; height: auto !imp=
ortant;"></span></b><b><span lang=3D"EN-US" style=3D"color: rgb(127, 127, =
127);"><o:p></o:p></span></b></p><p class=3D"MsoNormal" style=3D"margin: 0=
px 0cm; text-align: justify; font-family: Calibri, sans-serif; line-height=
: 8pt;"><b><i><span lang=3D"EN-US" style=3D"font-size: 9pt; color: rgb(64,=
 64, 64);">TEL</span></i></b><span lang=3D"EN-US" style=3D"font-size: 9pt;=
 color: gray;">+86 18602957745</span><span lang=3D"EN-US" style=3D"font-si=
ze: 9pt; color: rgb(64, 64, 64);"><o:p></o:p></span></p><p class=3D"MsoNor=
mal" style=3D"margin: 0px 0cm; text-align: justify; font-family: Calibri, =
sans-serif; line-height: 10pt;"><b><i><span lang=3D"EN-US" style=3D"font-s=
ize: 9pt; color: rgb(64, 64, 64);">ADDR</span></i></b><span lang=3D"EN-US"=
 style=3D"font-size: 9pt; color: rgb(127, 127, 127);">&nbsp;3F, F1 C Build=
ing, Chinasoft International, 3639 Yunshui 1st Road, High-tech Zone, Xi'an=
<o:p></o:p></span></p><p class=3D"MsoNormal" style=3D"margin: 0px 0cm; tex=
t-align: justify; font-family: Calibri, sans-serif; line-height: 10pt;"><u=
><span lang=3D"EN-US" style=3D"font-size: 9pt; color: rgb(79, 129, 189);">=
zhangxiaowei@chinasofti.com</span></u><span lang=3D"EN-US" style=3D"font-s=
ize: 9pt; color: rgb(64, 64, 64);">&nbsp;|&nbsp;</span><u><span lang=3D"EN=
-US" style=3D"font-size: 9pt; color: rgb(79, 129, 189);"><a href=3D"http:/=
/www.chinasofti.com/" style=3D"color: rgb(149, 79, 114);">www.chinasofti.c=
om</a></span></u><span lang=3D"EN-US" style=3D"color: rgb(79, 129, 189);">=
<o:p></o:p></span></p><p class=3D"MsoNormal" style=3D"margin: 0px 0cm; tex=
t-align: justify; font-family: Calibri, sans-serif; line-height: 10pt;"><s=
pan lang=3D"EN-US" style=3D"color: rgb(79, 129, 189);">&nbsp;</span></p><t=
able class=3D"MsoNormalTable" border=3D"0" cellspacing=3D"0" cellpadding=
=3D"0" style=3D"font-family: Tahoma, Tahoma; margin-left: -1.7pt; backgrou=
nd-color: rgb(236, 241, 248); border-collapse: collapse;"><tbody><tr style=
=3D"height: 18.1pt;"><td width=3D"418" valign=3D"top" style=3D"width: 313.=
55pt; border: 1pt solid rgb(217, 217, 217); padding: 0cm 5.4pt; height: 18=
.1pt;"><p class=3D"MsoNormal" align=3D"left" style=3D"margin: 0px 0cm; fon=
t-size: 10.5pt; font-family: Calibri, sans-serif; line-height: 8pt;"><span=
 lang=3D"EN-US" style=3D"font-size: 7.5pt; color: rgb(89, 89, 89);">This m=
essage (including any attachments) contains confidential information inten=
ded for a specific individual and purpose, and is protected by law. If you=
 are not the intended recipient, you should delete this message - any disc=
losure, copying, or distribution of this message, or the taking of any act=
ion based on it, is strictly prohibited.</span><span lang=3D"EN-US" style=
=3D"font-size: 7.5pt; color: rgb(89, 89, 89);"><o:p></o:p></span></p><div>=
<span lang=3D"EN-US" style=3D"font-size: 7.5pt; color: rgb(89, 89, 89);"><=
br></span></div></td></tr></tbody></table></span></div>=0A</body></html>
------=_002_NextPart168841144224_=------

------=_001_NextPart873717258062_=----
Content-Type: image/png; name="InsertPic_(10-12(10-12-22-44-41).png"
Content-Transfer-Encoding: base64
Content-ID: <_Foxmail.1@809225ca-f74d-7c0a-5f4c-37dea29b83a5>

iVBORw0KGgoAAAANSUhEUgAAAS8AAAAQCAYAAABHhfkUAAAAAXNSR0ICQMB9xQAAAAlwSFlzAAAO
xAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAAA5oSURBVHja
7ZwLmI5lGsffMQbDGBrHnMeIxqEwtCTnU5tDSsYph5wakaHakNCUCqHEdtSJnGbJqqsiypZNDqsQ
atoOW10ppdVpr7a9drP3bX4vj6f3/b73OyBdvuv6X2a+73mf433/7/99P99w8vLyHBfyyhDkCw4J
epuf+UFeVwpuFBQL0j4ayKu5YIHgb4LaJ2sca8xSgusFTU7FeDHONU1QJoL2xeM0bglBa/03Tv0l
/dr3+hSeaXIMzxYVNBZcHq89lVeCIoL2lQUpIT6/TTAnYF+lBTV+8b6P024TLA/YcVvBEcGwCAxe
yahIiDYXK3kK7hO8LdinCxVcJEg8RcaTJNgq+F6QGqB9MUHJCPuvIego6CEoG8NcHxRMC7DvZTHC
3QHaVxK0C9OmjOCgYHU8zkVeswR/EZx/ks5Ug/NcQcUw7QYLFgvKxzBWOcEmey3s2WWhHJt2Lwtu
jXLsuoKv8Mt4BRYlw72CZmHa3IzQ0Pl/LegSgtw2u4TIs1lKvD5tD9hjmw0SBVejNpbhVMnhHFde
1QX/ZcJtQShiqih4BpJM8GkziDaPcdCqLHpi3KkxHMB1gtsFeUGIRl5/FHwBuVwYSt1gMKshMSWJ
SiaxWW2vEHzO4f5PcFjHiGFdTwi6+82PuX8k+EHwJE61I0yf7TD+DgHGfiNODlJNsEfP3Xivs2Ch
aVNE4qGCGe45yquv4NwAY3wqGCWoL2hq2qC8cgTvse7n1UZjWIuS5E/qH9b7LQgeg0IEmfNw7JwY
xlcC3qkEqP4TZR/tBY8Ye/OzEolHu5L4yib8tRwC5BtV5mHU15WIkomCD/RMfNpq35NNQj+aQiij
EZFTBblEvzsEtQR/9opA8qoi6A+h/FuwCAfq7MWexnOjMBAdY14AtaDz6iN4GqO6OIYDzaeP/wha
BUgb/8QBqLr4UDA2zEEcQgVp1B5vfDaMfazB77cIxgnaCLrGqLo0Ku0QbEcpZvrsYw/2fB9BYZnP
mRY35lyghhhm/HsEP6LWO8WBwEYK3iGA5hLItpo2hSrcxFnOV9ISLNHzEQzUczPa1hMMENQhaC2m
3WTGSDLaNqWtkkdLwQ2RqGmjn/MgrsOcje53PWuN/QzFriRxkeEfek7rBEsF6R79q/0M9BlbffBZ
wQpBNoGraJRnMYA9niB4lZ9VVJT2SCkvQACpuk3RoCd410/5IWJewL+W8WwZr/aIgb2Mv80kL82P
XxFsENxFmnQIg6kA43b3mHAGamsszv2QH8Mzxu8ED6Nk1qOCGvq0r6mfEdX/ys9qrFtikcEq4XFi
T0XJPDsR6bW+9rHgE6LIOWZqhANdKpiJoX3PXjW0I7a8LvEiXtegMeDaUaynE1H8Tc6oVBjFO4yf
R6hhe5B1AUFLI+eLekZhxte1vo7yVuO6PkbiupZ91716CgKp5J65qi9BI8HvCZbvEPFVsU3VPWRP
Jlup6BFKFZrSrKLfotZ5ahqfSfaxjmeOeCmNALWheUpO7M/jgs/M/cb2O/NzKns9DzsoYNyPCNiN
rf6b8flIfj/X+rwL5KjrfsklyQjXUAQCnstYYyGYLRB6ohUYU1HDKyGsTgTmAh8y6kVfS1G4iWHm
s4Q0eAwZYeljaSMsORNDWCPYhXyfjyPn++X/GNLTyPFJPm0qEA3eV6PkvSGM08ajfT/Gv4zNWwp5
jYnBMVIoYN5E9HjdNQDrIKawZo1Y05Q8Q0jqjZB2DsSvztPCo62+/yUO1Jz3Lke53sBcNADUiaIw
+xAkmgHZ55pR3mh7B0HpASJpC1OlQc66198xz8U4itYeq1lO3kTTCUhLn1kVB8U1ByeuR2pb2UdB
Po099KVEkcxn87GbFOuZvtRNi3FOh70UNGn/P0njFxEUXor0IgqnHWqfk0tsRgrW2vg8lX+r4tR3
4y/DNfux6qrb2PMnOf8lpIfljHZDaXPIfD7Ci5jtZCg/YCuq9qoY9Tw3oCxDpVdA6TXE1zqTrZSx
+r4Gm6/J7/fi59U9i/KFSnofJNcSchxoklcJokEPBtwDoTUJVbRUSSvYjzr6NBy5kN9mc3jvUPe5
wKfdStTCTzjlqmhvGoninyClZxOBq4a60eHzZ1BUS0MZMZGpIYakUfZCI6rWQxLvN1LfbqxvErW8
IThVVoTrakhqm2w45xeMsYN5pdA2jSLqW0TmTsz3fleFEP2vRynu4/f9FEurGkEgj725D4f/Q5Tn
Uha7U+d72bBFjfhTDFJrbj03nLn9A0dX0nqDwNvFpwTQn2D5tqukPdr9ndpLd5Rkmyicfjg1zY2o
pxYomfluKUFeo9UGrEJ3Cqmt1vHuxD56ms5PIPmIDOagUTaYaZHXnaRjs2MIJprCNWA+6yCNNaS0
GojXQljfUV/LJMXfzXzS4ZJ6HrW4HQiizaSmC1CKt1htR1NueR7l9YQpDtxGi1AbCTjANzhFb5TK
AxhLugcrfkYRfIVfmsEGP0W0ro1DqwS8KgTJ9TIk9hbqBpWjPIju1Jh6IYcziMgdfNp3I8dfizGn
h+g7izRsAISvDt3AlfQ4pqbk36qTQ1QZpOr5rE8J5bkI1+TK9EuM9+pATA9TixplBh95LSfSPY/h
zCVKJ3H2Gaz3XT5Lw9GVDNt5zGEZaV4BimA0CiYh4BqyONufIZY89ul11ubeZGdbyu9niOsVaoYz
sN/SZhHZg8CWUJtcASFvc+2cNntIwe/2K2kEuORoif18jHLpyGfqJ/P5WW3xWuO5mfhYI3wukxRa
iWCAqdAgBSXqf+kZh5jLQs7wsgjXkAzhzmB/N0K8VxHQy3Jumnm05ny6MP/V1Hw3UKLRAnxfq/9J
tOkKKVZHHKj4sS83JmILuxm/FHadbRbs2zPhbDbya5TKczjYIgZqb3Xen0Fns8gRIb4WoJH8NuO9
Z5nIOA7MvPXR9/pwWB0xKN2krjFEkn70MREi1J8XhinYFzVkch1SvUVuHcIpvGUZDDnvZA/0IOob
/TSCqL80ZTH7eoC071snxK2Mjyq8n2cXYOjPknZ9axWHUyDWtax5A0bW0epzKMrjEQqp+UTIAtRK
qpW+vIr8H8zeunWiT+l/oBPw6xNE8yOouAM43j0EUSWcIlb7aajn1qjGDtS8ehpthli1GSXyHKOI
n03QHeVGc5xtQJT2VYKUvSS20pV6VyL43LV/gth8K7jPMUosGzhX3Y9mHnaZy9o1e7nBYy6J+OZ2
s/4XYA3FECkfkpa2NeuolCfqGL+7ZR0VAvVZczPO3k09x1hljvXYpBb41/D+YhR+klfphLPW82xF
TfIwfR+NPLdiLLnkpAeDFPoglk+oEy3AqDJJSXSwpkYBcIkrlVE/y1l4ARMyDW0tfWezKCW+Fw05
WzYK42pACpKNcQwI0fZ2FERf5/jNVxZpmNYRhhnKqhrk9jURRcdo6VHE/cZMkVUROYWXGHrYdSNM
taZykP2d48Xt94l+H5wgrQtTEo1cr6kCNepA7Tz6LUXKcSmGPJr+B1pqaSOOOR5F8T6KWkm1Cuqg
lhPiKzMe1+A/ckaqXKdjh0fMQGAUe6vw7xj+vQ7yXUHK2x6HKIKjjCQQT0LVv2mSh0EKm92UPwr7
0tpvLj9Pp1422QiA3Q1/UH9bbz0/lRSpKmvSuuMgDztKgwQuwjZHeRBXTYjHTeFmsDfTA6zj2Bee
UZE7UZQlIKVjZQJsRpX8xRYB9sGuX3UFAjXV2exJS5RzKwJJD+zuQeZtZ3g7UbL1+b0W4x5l/TSj
YTnShqwwi6xE1N3FYSmBPQqBjaOI18CI/m9hPEpuQ4z0cKtHBMt3c3in8Pp6NiT3OAd82E0rIzCu
Ss7x25MXIc/XqAPdZLSbAKu7aisDZTMYw/K6pazFobo1o24eUnwTzlkRqdwBhxvPni0mbckJs45E
66sNh1Aqb0Oyh8KRO2qjg8d3dWYZCqAxZ3rArPdBzjcZt6jPQQ6JUTh8ZfbjXeoZ/VFhzbCT+1EA
6ZBLEmSp6vkOnDyLvawGiR/kjF2V4wbTPrw/lECy2KMEsjlK4ipJ+tzPSHcqYbuuHRezlMTLRvo/
EbWr9d2tOHEuPpRDytSU9d+I4n7UJDec/ins+QHIYA593ow4uTnCdV1uZydOYZ21YZjnqrMGrRfv
4b3m8ERRAvcl1iWGBppVKLMci7DVBu79xTg+RXiNTDV9inhjIZdNpF/jyfFLY1DNfBbUmYJeE9RP
PZxlisf1/30c1hIi2DRk8lbkabdQdShr4ddAeO7N2Hsou7tQFppu3W0YwBGcMgF5v9w5fn3fM0Qa
t5uIpwo03yd1TsQhd3EgEzDMRs7xP4EaHKGB7cJol+IAY5zwV88jPcirCPWt0vzuXi70D9PXLCfg
X1d4PFsD4voOYs8ibTVLCKsJCp34XVPVK0L0WcHx+JMlFMEL1LOG2sEPW5sa5TpaUB9ybw2nMOcL
80787tfVzK89waY880onENWHrBaQHTwGQatdFTfsqLjHHNzLoT7YfBtIbmWsN8FR7ona+l4vXwjx
THnIa48T4CtRXh1kINMq+nzd4DpUSBlkn8q/sXx+9EYtwCQbo7p62cVdp/CCoCuH3AqnTucgFkbx
fZVxSMwR9JVkE5xV2J9rPd+T9dYNM1ZNo2h7RZi6wjlxNJK6jsdXIyIlL59A1ShAX2ovVWKYf6tQ
qRoGvRGF1/IkOVomqW+0F0IJzol/AVDV8fimOCQ3D1Wit8KZJ2k9dVBtg5w4/XlQDLaZFuEzJSkZ
FYuGvKpgLGkBBkqm8FbcMILGMSw2DTVS1GDv8yG53qfrEH5rIA3ueAbNtzrq9ysnwu/CBYz2WpuZ
cIrWUgJ7bhO0JngWwckrCdla+TQYaSOvdPUs4r7Pmla0PcPmXIZyxbQ49lmNovfMs3bxGyAvDlVT
rXNPg4EmnD2UU7LPyc5J/C+MTnYtJY59lbRvM8/izMH/AR9IgKNCRH8dAAAAAElFTkSuQmCC

------=_001_NextPart873717258062_=----
Content-Type: image/png; name="InsertPic_E9DF(1(10-12-22-44-41).png"
Content-Transfer-Encoding: base64
Content-ID: <_Foxmail.1@0816baed-6ddc-3b9a-67e6-7a59d4354048>

iVBORw0KGgoAAAANSUhEUgAAAaAAAAAFCAIAAACM8q/nAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ
bWFnZVJlYWR5ccllPAAAADNJREFUeNrs1kEJADAQA8Ee1L+/qEltlGNGQh5Lpu0B2OgmsQKw0nhw
gMABCBzAH54AAwCMGw6IdTV5ZwAAAABJRU5ErkJggg==

------=_001_NextPart873717258062_=----
Content-Type: image/png; name="InsertPic_E9D8(1(10-12-22-44-41).png"
Content-Transfer-Encoding: base64
Content-ID: <_Foxmail.1@915630e2-8567-ac54-e109-1dfca433392b>

iVBORw0KGgoAAAANSUhEUgAAAKoAAAARCAYAAABNezc0AAAAAXNSR0IArs4c6QAAAAlwSFlzAAAO
xAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAABYtSURBVGhD
7ZoJdFXV1cfPve++IfPwEoYAAcI8ySwyVapIl4yCHyBataAfUAFBQaXMICjaYgGBImppRCoIWESl
CohIQCgKVkgIJBCGhMzJy8vwprx33/c7N0MDy6Fr1X5rddXLurx7z7DPOXv/z3/vfW40Mfqtb4Qi
9ougMAshAkIJBvkVIqgo/G+qKROjhKJ1ErrfqPq3X+ZQIapdy5b3vrL83z7WTwP8R2hAE0I/urzX
td9832yXnk6yC81aA1TNJoQi8dvgCgaAczV1Vgolvhtcfjeg12/up/uE8HObLDX3TbJoe6uM/whV
/jTJf6cGAKoi0WVcS0+3fkCo5oUgywSQVi3ve217bRVtIFpFBWCezym7yE1f4wqIYLC5UJT+sOBh
nkt5pqEkZgna4Ehkxgu/+2+8Z1CvUd8bUHcQAd8VofuOwt5+mvJPIlqJEar1fsZCxk/XTxqo0UAd
2GrerLYPhMe9CchEChF64CYlmcBqddUxYVUmCb/aWQT8NdSpq9XCZJokdD0TbL4izNY+1Omwry5U
JQpQ3ieCAb/Qlf8R/mqr8EcUC5vr58IaslcEPL+hf6YwW1obfQJQtgqIVe1+oXv/aRsdOHCg1fnz
5++sqqoKa9u27ZmJEyeelJ2Tk5Mb2Wy2XhEREbnDhw8/21Agdbdfv359CPVfPPPMM8f+6cH+hYZL
lixREhISHvR4PANDQ0PPT506dYMUR7m6YsUK6UrqL9bUzeFwNAsJCUkdPXp0zg8N+20yfqjPv1Jf
N97atWsbO53OB6KiokpKS0vfYR241x/nKikpsR5JSRnk93orbgaqpEBFqWIYkwi5xf9KkhTB86Iq
2FeEhL8vgp6a2SgwpzVcCI/zaVx8Z8KCJ4TwEdcaHdoJLTQWgF+ioUtoZouweOYL1XKnCBrxbolQ
9RHUDQHxAUY1w7h9DOYOipsM911L37JlyyPFxcVrqqur42SbjIwMsW7durWzZ89+CuDeDxg3AdQN
AHVWQxn0edrv908MCwtbRPn/C1AB6bNFRUWrA4GAwLhbdu7ceWdefv7Kbdu2/fbhhx/eVzc/Cejf
/e53rwPofk2aNBlL+XcCdevWrfexznnIWswG/ezHgch3S0lJSYn6+uuv393yxhtpUx9//Gk2+s/K
ysrWut3uVHrVeeAfZRoff/xxx6tXrx4KBoPHbwaqw6GI0JCaQdyeW4JNCUoQpAZtRlwpvbQRDtAM
wuRhslDV14Sv6h1+Ndx5KXydDWtuED7/eGExAUi1GEAe5NdOmJAIoc+GifcK4d2BAAtBxBmg2gH5
W2U290Or3b59+8CCgoI/6oGAKc5uXxMSFpadnZOzhJ09h7p91V5vYwkKu93+NQoOz83NtWLMEik3
KibmoKqqRa3atn0fYMhEUsAG1TBEo969e1cOHjzYVTf+jRs3wtkQUUOHDq2ivKyuHJmRhw4dili9
erXD6/XWt5f1L774YtOkpCQv45XK9wEDBoRTNkXXddGjR4+xlB8AjOvKHI5BLZo3X8ccTHVsdM89
98Qjr52ce6NGjS5L9kKEZF2/nB/zqOjatatb9vn973//S4AyEE9iqWM5uR6YOH7QoEFyHeVyfFkH
Q9teffVVV2pqqjSy+u677/qR6ZVyYmNj4+fMmZPfUOd4nfisrCzzxYsXi3fs2EFSIURhYeFg9Dss
lkcpkzb5kZGRf+A+iiwjEZcsK8GBvMI6ebU6DtauofH48eOdzZo1q2U7Ib5Nx2zmzj6fT8DWGbcw
qgP02YIwmqTJWxgN3AQl1SkXhK/iCOCE4mVICVqDIp6HLrDrTGEi3sR3C1PgunArc4U5kCb8ifnC
nDeNSZ9f3ufatKUprS+IMNMDtB8C8Fsbi1FlJubfLqqVw8LygxgVS5cuVWDKhbCiKSoy8p0Zs2bN
k2IwXCuXyzWHe4zP7zdYtqSoaMKVK1dWAkz/hg0bnj127Nie9evXj7FYLFabpikAea/JZFIARk65
0znpiy++uIyBHuZOjY2OXub2eh/XNM1Ov+Jz58699sQTTzy/efPmaRhsEeXxy5cvz8NQz1P+R5it
e3Z29rqA33/H5cuXKxhn3QvPPLPuwQcffB+lt5dAzcjMfHnlqlUrvR5PK9hCMLfNLVu27P3YY48Z
SS1gaM5cYpF9HcZyRUdH74f52XfeQow3/sMPP8xIT0+fx1oXw6YDZZ+z58693Soxcak1JOSbl156
aQP9Ox1LSSlNS0tbNX369I0w8xTGnxceHv4BwJZM/feY2Ngh4WFhR9lofZDddv3atbuenDPn14Cv
Jcy/lrJhUi+9evVKa9OmzSzG/hme6Fk5Z8Yd17Rp0zjml6GaTD3ZULsvXboU98EHH2ymbjhT0pnf
jgkTJjwpwW6Pi9vPegqqfb4qZ1nZ6O1vv53RskmTSeezsi7HxMQsgZGnMVZsytGjxWnoeDo61v3+
NthMhFosp28GakxCpPAKjKuECL8/gsGK6neYTlYfVIYAvD8Lt+tp3DiO2hwU1W4fyRJuNZhPHCrd
KHQr40uzT1j0e4VivleEFowD07NhUMvS0y1/LULFddrn4O33EQK8R1szzxyQKfJ4bHoNW8uY4rsv
WK/F2bNnB8mFhEdE7KxricK28Hw6Pj7+OgbfbJQrigcDnUDR41D+EzNmz74AyEYpipIN0KMp/wUh
hykqOvoNi9V6CpDfhdt9CPCkwcJLAPQOlLmnpLj4ZQy14o033nBiyFco/4rxZjPOExUVFauJKy9g
rG2ApHWjuLinXB7Pzxjn+d9u2VKpqWq+BCmAu2qzWk8Clha062I2m0voezxQXX2+bg1Op8MAMH3S
YUYbhv8FbQSs9zrvZ3i/k3nMZO7FhDxWAFBcVVl5pFF8fDNc5UrkSJZ7GONPot2GA/v2nfB5vd0d
ZWUd6NsBnV2BXZ2weTc2C6oJ/wi9dCkrL59+4PDhP7G2RbyPhMlmM2eNWHENm24d691Nfw29Cfr9
raKq4lxlZeU93D0c0dGR7733XjJjDmfjL2Nt0YwxZ/d77+Xc3rXrnxlrgOyHHl+z2mzpVS5Xv5Kq
qvsAex5zXIbsnehmN+t8uaikZAXe6i9VbndTqRNLaOhVgFp7bipLvDq7U/nIKLLovSjJqjE0BRKo
qpoE4A7BeBKJiuHyVU36f3kq4BWqSDHKjSNZilVL3YnCNuqgeT9MG6KJgJeTAs6oFGU2QJ5T08eI
Sk28mwkXvg+jRh3uKB4lRrB4HwolBq65HnrooXR+0mG2ZtS3k7u41OEYm9CoUY9yRRnHLnU4S0oS
JMCtFssZlGmmnSnEZjtOXPu/uK1HULYEqhkmO3hbjx4PVFVUlPCuAa4SwJFYXl7eVTI5yrUA6oh2
7dqtYQ6ZxMeTAE5STHT06zDCOlz9SQA3rrC4sG9CQvP38wsLJ1nN5r1PPvnkU8xvAGs4DiMdX7Ro
0ZiGC3a5PB0lqDWL5RLzi5EhAO1SZs2aNZUQ5HHGvJM5pPfs1m3PiS+/nGC1Wg8vXrx4IqHEW7Bm
TIsWLXawAa4BwDRi9LFnMzIeCAYChtFhrY/uvvvuyZ999tkGCRzaLJ85c2byCy+8MJi5d3cUFfkp
m9+5c+c/0/cqXbpz6wDXunfv3k0jR46cwtqtsP9YXLdz1apVueiykvm1lUwaEhp6EnnL0V3M/Pnz
Z1Q6nRPSr1zJlGPT5iPWMB2vNl/G3+jZ0rx584Pckyrc7lKfy6X6PJ7iSperdZXT2QQdtJf9WJ8E
qmpbunSJIsbvUkWrvPeX28t2y8qlJ27XlnayqGL8+KAY83aIkFk/+Y6R6ND3ZiQZ5EfZrS6bcsmO
xkmThQNYeVGmhXAQG6wNhm/tQ3s5lt9lxI3fdaEsVbIOBvERsznq2u3Zs6cPO1xFKY2p18iuz8rY
SbPZukhwSleVm5NjxK6hYWGXYYskKYddbiRUihLsaSzGbM5kdw+BSRYwRnV0ZGQ27XpiXGffvj03
HTt2sjXKHoqy/wSAfTDrsiCKNeakaV9JGTBLI2IvGbKHuKqqpMEFcfRl+QtrDZBtmZM86rvpQmYX
Yw5Wa/rV69c7yGf2hDE/5tSrhpnsqdC34fapM040AEp/6oKA+Ods0MHoyA0DnwCc3iqPp7NJJc5q
3Xpx3759iz799NMkKadL797HcPWRAV1vzXsecXX5kSNHZpAwjY4ID8+SMSCi1bDQ0PRNmzbFo7e2
zCtTgnR7cnJH3puin3M5OTnN5BzwFqfl75tvvtmIOlXHBszZWDu2+EL+siE6SVugs0z0fzehz3yT
SfWHRURmw6K9mG+Zs6rKw/y78OxMTEzMJukRMWLk9ueEm9Tnkr16aVY8zKZrQitSxdtBi3j7LRmI
hhOXpooAVBdUdBjWKoIqrCrJNAiguJUGyU/AVMl8QHXdUaiReCnCpANOvRaAuPmAVlnTj3PbIO/y
kuepemUsAM+91YAN37t06VKI63ex6LB9+/bdNnny5FxYog3x3yeqonhx/VslGFFIRq0RjfgQoFzD
oAYQMEwGbdpJpakWS5os87q93ekfpF3itWvX/oARUk+vWnXHspMnW+zatetejFTucFQUkwxMxaAd
PS7X7Q6ncx4u/rmYmCgDMLguI2EjqOwtfwHNlTKns4UEBnMw2B8jdJdAhb0Mw9ZdnTp1MjGn9rKt
ZOnc/PyRsh0b7JtaI3eR73Z7zNXLmcUj5DPtTtX2ZyhN3HXXXWNJ2C4cPny4HxsimtMGJ3P9jWY2
506bNi2NODKK8dsBgnLYI5s5dMSLRgLqL7lmoZ9ZcXFxL8KMCwDnfOYyiGPti2zaROamMaaxudy6
boQo6EjquKSWoY3kkXG7we4mXH0Ga25qeAhNM/qxwTvw7sd27Wi3inHPnT79wh2zp/2l9YGCguHM
6wr9ZM7QlHWfkgkhRCMmd9dyWmghwhYifOFwqM2lW4pL3SFlZ4tinMIGcELca5McWXrvJC0pwqLH
XXRGnW0bUdGNTWCr8IWk7soaSCxbEyUIEaM83vn0UItJi/dV+/yAQNKthoWqc32hKR9mJRTIVkOT
8qKSbO7h0nJ+XbtBkBAvAqqCAj1fF4V8frppTFlDA976zNniNXbiTlzjZDL9t9atXfspcc9gXFQs
IF3ILo6RfVCiDAWEx+vtVavUHFzn/VKpMB4h3dX7DFBYLBdk9vv88yu7geByAOmXQEe5/ntfeeXO
vMLCBcyNcCk0l+RgF5lzYxjhV/GNGx9wVlTMk6C32ULfQcmDUe4EWKqKmG+axWyu6tChw+4vT53a
KsdJiIkxGJWTiiZyPq7KyjGEAe5ly5Z9SIKk49pjKO8o2+ISc/Ly8nogU8a26bhTs4xrefcj8wah
Q0spg7VO2r9/vz86KuoT4tBpAHT2yZMnU4j91hPeFKi6vlqGKugiS7I/Lr0n71HM86v+/fv7Nm/Y
0IF3yeDZgCdByuQ2M5cJbMCFtXo7j6dKqN0snd7Ztm0S55t9JACxcX63bt32MubzjDmSE5fP2avP
yXlji2SSy6fY/ILkNxUPE8pYkt2LqWdquhzLP2zYK0NKS0oW8G5mU1wAwLFGnK5p2XJMbX7iyagq
3bIVj56Fl5ZMoyuqkq5HBfQZiXmP54d2dcqGTVyOqExfSLJZM1U0Nue+6VfUZzBCqt3sCFva+4OX
1VC7/GLFlS8qnd5FquIzBSx6BXRJDq+WMWgLu7XE2new+rpsFXQVdqzymRcETcE0wkyPZlLTgLOq
mwIFX035xrHiVP8f/MOCESNGzCUDtuDqxhKHPoAhigHfCyQ3q8lqXwdU+TEREQYT4Y5DMMQV3Egu
9SbmkwUQClGiFUVfHjl27KV7Ro2Kt1gtlSZNywKEWwHxAHb/XQXFxckAZT8g6YhxT5CoHMQ9r+Vo
7HB+QUHQbDKlNWnadOajjz56auPGV1uRp/wauRMwRCaGmow7vXDmzBmrWVX/Nv6RR3LYTDLs2MPG
6gEbT1JMpmhAapyjAjo7xionQTwf3qJFRfDUKQ3GyURGzluvvRaLTOnOUzlayoX1djGnroBiMuux
jRg5cgZxpB1ATUXOdOLutITGjX9V5HC0Y+1FMO+J2jGaEy4UIeeosWmESGBdRZRJ15zO7+0QwDzW
mYIOD5I4DWAd0sPlUJfO/Dtl5+a+RHJ3Grn5yDk/bNiwVPQ1UyZiEMghGUZgg+mw9z4S38WwdvrY
sWNzODmJZ/NUoOMvOycl/ZGNOETmBPRLRtYh7jw2XAbJX7ScE3G64S20Ci0iLghFmzXLY3DxJhZ8
2aJZtgR8vsNp7qZx9lBhADXXbbPpJtXm9Qcr8eFQvjjm9vlLFcUUWun22yL5OxJ5ya8JTMIt9ODn
alDpDp2SGAReZdv9knCH47eaq8IfounBQLlJNfn8KFn36S2J9JsToB6Z/df2Jrtd/CBQOTt0cFb3
S3mcAstF3HbbbUUwbQExqejWrfmzsPuCgwcPFst34rKJuBN9ypQp5Rs3bhwHAHXOQMuJbydIWwFw
x6H1680DBw7sh6v0cU5ZNm7cuOELFy5sDxOUcMSTRybaGBlu6sphtx5z585tQ191yYoVlzCekQHO
mDHrueTNmzdm5eVFE45cIZargGHMJCd3ADaI3csfPwiBPE64Nv8VQ0Xj7uvDnH79+l1lvF6M4x0/
alSFIytrDEAI4P5Ka+X0kXLklyySsg3I+BAZHFhE35D6mDdv3niSlXYY37xmzZqs/Px8D6HRReqO
cK5aJsdG3sd9+vTpzq9h2+aJiVvb2mzvAqhS9ODdmZzcN+P69UaEN5msMTBjxgw783fIOnTQH70l
xtrtlQCvjC+CllGjRkHUZYIvbRvxDrspa4KsG9iiGOZX0OlQ1lMN6KuOHz8ucwqZqLv74tJnjBo1
fNTcue3ll60GOpYfnQQnLgc43iqVsjWCJVlWjhA8VbmDP5oq5lm6ABnM1h8RVZrNMWSOBezoO4LV
1a/Q6xN7bOxxzh0XRNrtn9QBUP7CovJsqQxZxpcAACgTKZN08w3aBdh10bRpq+j6F7qqtuJwYSj9
clFoNQzTUOT3PsNk125tMHjwaCNOlCCVF4bmY4MQp06dkqA1nimTP8azvDgP5WhD1B9SSzfJ51X5
xaVOhhG2yIs6L5m2caQkGbLh9ej06Ry/ySO4mouTCCm3vm9dOYaR875p7hIMzMtoK3UAU9UfEX6b
HGRcvWlwXogtjSwbkBpVAKaCH3kbF/qSQDDAUFsvPwoYHwbkNfHRR+X4xhw46Jd6qv8QwLOT+1xd
W6lDCaT6vhMn1veVZehUYqhep7U6rtfFKXSMHr9VxxBCZZ1seY4qwdOegukArAfPsdIIPDciPqj/
bqtVV5f7TSb5DV2GB27S9v4E3ZBhsG39LP/xIAOPFjK/B4wVZMNjiDvaMlBDQJOQBS+C3b/T7V6e
dUBbAFh74x6wl/0fZ7jfMsBPRf9dGgB/1ddgydfIz5M4SoiRn55w060BzkrRpk0u28XQiMPjKY/g
HIzH+8jAlvuqq2O5NxIkj3CVlw8OJZ6R7fiCEbh29SoffLRJfJ2RuzigmUxdAG0CScqNBur1AMye
9NcAsANAhwLoC7TxMR+ZLX/832WKn1b7fRr4P0jM2PMolW6WAAAAAElFTkSuQmCC

------=_001_NextPart873717258062_=------
